---
services:
  auth:
    image: quay.io/keycloak/keycloak:26.1
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: ${KEYCLOAK_DB_URL_HOST}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm --health-enabled=true
    healthcheck:
      test:
        [
          CMD-SHELL,
          "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;",
        ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      backend:
        aliases:
          - ${KEYCLOAK_NETWORK_ALIAS}

  database:
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${SUPER_DB_USER}
      POSTGRES_PASSWORD: ${SUPER_DB_PASSWORD}
      KEYCLOAK_DB_NAME: ${KEYCLOAK_DB_NAME}
      KEYCLOAK_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      MOMOINO_DB_NAME: ${MOMOINO_DB_NAME}
      MOMOINO_DB_USERNAME: ${MOMOINO_DB_USERNAME}
      MOMOINO_DB_PASSWORD: ${MOMOINO_DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/database:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: keycloak-user.pwd
        target: /keycloak-user.pwd
      - source: momoino-user.pwd
        target: /momoino-user.pwd
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:

configs:
  keycloak-user.pwd:
    content: ${KEYCLOAK_DB_PASSWORD}
  momoino-user.pwd:
    content: ${MOMOINO_DB_PASSWORD}
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "${MOMOINO_DB_NAME}",
            "Host": "database",
            "Port": 5432,
            "MaintenanceDB": "${MOMOINO_DB_NAME}",
            "Username": "${MOMOINO_DB_USERNAME}",
            "PassFile": "/momoino-user.pwd",
            "SSLMode": "prefer"
          },
          "2": {
            "Group": "Servers",
            "Name": "${KEYCLOAK_DB_NAME}",
            "Host": "database",
            "Port": 5432,
            "MaintenanceDB": "${KEYCLOAK_DB_NAME}",
            "Username": "${KEYCLOAK_DB_USERNAME}",
            "PassFile": "/keycloak-user.pwd",
            "SSLMode": "prefer"
          }
        }
      }
