services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 8082:8082
    networks:
      - backend

  auth:
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    volumes:
      - ../docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm --health-enabled=true
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      backend:
        aliases:
          - keycloak.localtest.me

  database:
    image: postgres:17.2
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      KEYCLOAK_DB_NAME: keycloak
      KEYCLOAK_DB_USERNAME: keycloak
      KEYCLOAK_DB_PASSWORD: keycloak
      MOMOINO_DB_NAME: momoino
      MOMOINO_DB_USERNAME: momoino
      MOMOINO_DB_PASSWORD: momoino
      # POSTGRES_USER: ${SUPER_DB_USER}
      # POSTGRES_PASSWORD: ${SUPER_DB_PASSWORD}
      # KEYCLOAK_DB_NAME: ${KEYCLOAK_DB_NAME}
      # KEYCLOAK_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      # KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # MOMOINO_DB_NAME: ${MOMOINO_DB_NAME}
      # MOMOINO_DB_USERNAME: ${MOMOINO_DB_USERNAME}
      # MOMOINO_DB_PASSWORD: ${MOMOINO_DB_PASSWORD}
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../docker/database:/docker-entrypoint-initdb.d

networks:
  backend:

volumes:
  pgdata:
