---
name: Backend

"on":
  pull_request:
    branches: [main]
    paths: [backend/**]
  push:
    branches: [main]
    paths: [backend/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
          cache-dependency-path: |
            backend/*.gradle*
            backend/**/gradle-wrapper.properties

      - name: Setup Gradle
        # gradle/actions/setup-gradle@v4.3.0
        uses: gradle/actions/setup-gradle@4504a95ca57b383b150e5f64cece035031420365
        with:
          gradle-version: wrapper

      - name: Linter
        working-directory: backend
        run: gradle check

      - name: Build
        working-directory: backend
        run: gradle :console:build

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: backend/**/build/reports/
          if-no-files-found: ignore
          retention-days: 1
