---
name: HadoLint

"on":
  pull_request:
    branches: [main]
    paths: ["**/Dockerfile"]
  push:
    branches: [main]
    paths: ["**/Dockerfile"]
  schedule:
    - cron: 0 0 1 * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  hadolint:
    name: Check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      # hadolint/hadolint-action@v3.1.0
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          recursive: true
          format: sarif
          output-file: hadolint-results.sarif
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
