---
name: ShellCheck

"on":
  pull_request:
    branches: [main]
    paths: ["**.sh"]
  push:
    branches: [main]
    paths: ["**.sh"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # redhat-plumbers-in-action/differential-shellcheck@v5.5.1
      - uses: redhat-plumbers-in-action/differential-shellcheck@5fa026e4797665181a0f7c6fa4a73c09348ae78c
