---
name: YAML Linter

"on":
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - run: pip install yamllint

      - run: yamllint -c .yamllint.yaml --format github --strict .
