---
name: YAML Linter

"on":
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
      - .yamllint
  pull_request:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
      - .yamllint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pip install yamllint
      - run: yamllint .
